backend:
  name: git-gateway
  branch: main
media_folder: "assets/images/portfolio"
public_folder: "assets/images/portfolio"
collections:
  - name: "data"
    label: "Управление сайтом"
    files:
      - label: "Галерея Портфолио"
        name: "portfolio"
        file: "js/portfolio-data.json"
        fields:
          - label: "Проекты"
            name: "projects"
            widget: "list"
            fields:
              - {
                  label: "Категория",
                  name: "category",
                  widget: "select",
                  options: ["private", "corporate", "brand", "yacht"],
                }
              - { label: "Описание для SEO", name: "alt", widget: "string" }
              - { label: "Фотография", name: "image", widget: "image" }
